### ISSUE TITLE
Welcome-logo (?) broken

### ISSUE THREAD

**Issue by mirjam-amsterdam** [urieli/jochre#10]
![picture broken](https://user-images.githubusercontent.com/44893880/48543014-d9c91900-e8c0-11e8-8fe0-015bb5febda3.PNG)

**Comment by urieli** [comment]
This icon is supposed to show the person's public profile picture, in the case of Google or Facebook 3rd party authentication. In the case of an account created inside the web application, it shows the broken icon. I presume this is the type of account you're using (?)

I'll need to see if I can find a solution, at least to display a generic "person" icon when it's an internal account. Authentication uses a 3rd-party library, so I'm dependent on them to a great extent.

**Comment by mirjam-amsterdam** [comment]
That's right, I created the account inside the web application.
By the way, even if you manage to solve the problem, why would I need to
see a picture of myself? (Isn't that rather narcistic?) I had expected a
logo of the book center to be hidden at that place.
Thanks for looking into this,
Mirjam
