### ISSUE TITLE
search results rather very fuzzy

### ISSUE THREAD

**Issue by mirjam-amsterdam** [urieli/jochre#2]
when looking for גלייכט בעסער ~5 
results are, amongst others,
גוט
קעסערן
געגער
רעסע
יעוער
and more - see screenshot
![fuzzy results](https://user-images.githubusercontent.com/44893880/48515554-50362e80-e861-11e8-94ce-d67ca1520f66.PNG)

**Comment by urieli** [comment]
I'm not sure what Lucene does when the ~5 is separated from the word by a space: probably, it applies the fuzzy search to the closest previous word.

Now, the way the fuzzy search works, is by applying a "[Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance)" to the search term. In this distance measurement, switching one letter with another letter counts for 1. Thus, if you have a five letter word, and give ~5, you can switch any letter with another letter, and basically match any other 5 letter word.
The Levenshtein distance between "happy" and "train" is 5.

So, fuzzy searches only really make sense if the number at the end is much less than the length of the word.
