### ISSUE TITLE
מקף נישט דערקענט

### ISSUE THREAD

**Issue by yankl** [urieli/jochre#29]
װען איך זוך אַ װאָרט מיט אַ מקף (־) באַקום איך נישט קײן רעזולטאַטן. למשל:
https://ocr.yiddishbookcenter.org/?page=1&query=%D7%99%D7%95%D7%9C%D7%99%D6%BE%D7%98%D7%90%D6%B8%D7%92&author=&author=%7C&authorInclude=true&title=&fromYear=&toYear=&sortBy=score&reference=

אָבער װען איך זוך מיט אַ „גוייִשן” בינדשטריכל, גײט עס: 
https://ocr.yiddishbookcenter.org/?page=1&query=%D7%99%D7%95%D7%9C%D7%99-%D7%98%D7%90%D6%B8%D7%92&author=&author=%7C&authorInclude=true&title=&fromYear=&toYear=&sortBy=score&reference=

מסתּמא װאָלט געווען כּדאַי, אויך אָנצונעמען דעם עכטן ייִדישן מקף.

**Comment by urieli** [comment]
יאָ אַוודאי
װעל איך דאָס פֿאַרריכטן.
אַ סך ביכער ניצן אױך א היסטאָרישן „טאָפּל-מקף“ אַנשטאָט אַ מקף: https://en.wikipedia.org/wiki/Double_hyphen
איך האָב זײ אַלע רעפּרעזענטירן װי אַ מינוס, אָבער מען דאַרף קענען לכל-הפּחות זוכן מיט אַן אמתן מקף

**Comment by urieli** [comment]
Fixed: see https://ocr.yiddishbookcenter.org/?page=1&query=%22%D7%99%D7%95%D7%9D%D6%BE%D7%98%D7%95%D7%91%D7%99%D7%9D%22&author=&author=%7C&authorInclude=true&title=&fromYear=&toYear=&sortBy=score&reference=
