### ISSUE TITLE
Missing words - how to hand in corrections?

### ISSUE THREAD

**Issue by mirjam-amsterdam** [urieli/jochre#30]
How do you want us to hand in corrections for missing words? Or badly segmented - the text states that we should not correct badly segmented text. 
(By the way, there is a typo "If the word as badly segmented")
below an example for a word missing altogether
![word missing - how to correct](https://user-images.githubusercontent.com/44893880/57676588-2057c000-7625-11e9-8f04-c45d64e004cc.JPG)

**Comment by urieli** [comment]
You cannot in the current version.
I'll have to think about this for the next version of Jochre.
The software for annotating the segmentation is already finished, but it's a bit too complex for a public website.

**Comment by mirjam-amsterdam** [comment]
but then there could be a dedicated email-address, couldn't it?
Best,
Mirjam

Mirjam Gutschow
Mariotteplein 15
1098 NW Amsterdam
Nederland
+31-20-3202086
