### ISSUE TITLE
book invisible when looking for it via author

### ISSUE THREAD

**Issue by mirjam-amsterdam** [urieli/jochre#31]
nybc205868 seems to be invisible when looking for it via author's search.
cf:
a) looking for וואלקאוו + nybc-#
https://ocr.yiddishbookcenter.org/?page=1&query=%D7%95%D7%95%D7%90%D7%9C%D7%A7%D7%90%D7%95%D7%95&author=&author=%7C&authorInclude=true&title=&fromYear=&toYear=&sortBy=score&reference=nybc205868

b) looking for וואלקאוו + authors opatoshu y / opatoshu josef
https://ocr.yiddishbookcenter.org/?page=1&query=%D7%95%D7%95%D7%90%D7%9C%D7%A7%D7%90%D7%95%D7%95&author=&author=%7C%7C%D7%90%D7%A4%D7%90%D7%98%D7%90%D7%A9%D7%95%2C+%D7%99%7C%D7%90%D7%A4%D7%90%D7%98%D7%90%D7%A9%D7%95%2C+%D7%99%D7%95%D7%A1%D7%A3&authorInclude=true&title=&fromYear=&toYear=&sortBy=score&reference=

**Comment by urieli** [comment]
This is a problem with inconsistent metadata.
The following query works: https://ocr.yiddishbookcenter.org/?page=1&query=%D7%95%D7%95%D7%90%D7%9C%D7%A7%D7%90%D7%95%D7%95&author=&author=%7C%7C%D7%99.+%D7%90%D7%A4%D7%90%D7%98%D7%90%D7%A9%D7%95&authorInclude=true&title=&fromYear=&toYear=&sortBy=score&reference=nybc205868

The ideal here would be to unify the various spellings for Joseph Opatoshu's name, using the metadata correction functionality.
