### ISSUE TITLE
why does an author need a first name (which needs to be chosen from drop down menu)?

### ISSUE THREAD

**Issue by mirjam-amsterdam** [urieli/jochre#5]
why does an author need a first name (which needs to be chosen from drop down menu)?
Why do just last names or wild cards not work?

Likewise, if I copy the Latin-charactered name into the fields, it has to be exactly as in the catalogue. Including lower- and upper case letters. Eg it needs to be Gilbert, F. S  (Gilbert, F. S. will not work either - there is one dot too many)

![author needs first name](https://user-images.githubusercontent.com/44893880/48516828-af497280-e864-11e8-8d49-7833cbcf2eaf.PNG)
)?

**Comment by mirjam-amsterdam** [comment]
If an author appears several times in the catalogue, one needs to write it out several times. Quite a pain!

![authors erroneus in nybc](https://user-images.githubusercontent.com/44893880/48541250-881e8f80-e8bc-11e8-8173-d01f1d2a92ad.PNG)

**Comment by urieli** [comment]
It should be fairly straightforward to allow wildcards here. I'll schedule it for a release soon.

On the other hand: hopefully the new metadata correction functionality will quickly reduce the variants on author names in the catalogue.

**Comment by urieli** [comment]
You can now enter a wildcard on the author's name.

See https://ocr.yiddishbookcenter.org/?page=1&query=%22%D7%9B%D7%9C%D7%91+%D7%A9%D7%91%D7%9B%D7%9C%D7%91%D7%99%D7%9D%22&author=%D7%A9%D7%9C*&author=%7C&authorInclude=true&title=&fromYear=&toYear=&sortBy=score&reference=
