### ISSUE TITLE
add search by nybc-number

### ISSUE THREAD

**Issue by mirjam-amsterdam** [urieli/jochre#7]
Catalogues like world-cat have the nybc-number of an item. Consider making it a search option for those that want to search in a specific book.
Motivation: I often use google-books as an index for books I actually own. This helps me to find a certain passage I would like to read or quote. Having the option for searching easily within a specific book of the Yiddish Book Center would enable this for Yiddish books too.
Example: we are reading Kreitman's Brilyantn at the moment. She uses certain words which seem to be specific for her several times. This way one can count the times she uses them and find the context within which she uses them easily.

**Comment by urieli** [comment]
Added in [44a88b4](https://github.com/urieli/jochre/commit/44a88b458fe37ac01803a39bc586dd7a3c9ee119)

**Comment by mirjam-amsterdam** [comment]
You are going to stone me for this, but I'd like to search simultaneously in both volumes of, let's say, Lifshits "Unzer bukh", that is: nybc203577 AND nybc211498.
Could you provide a solution as you did for the authors?

**Comment by urieli** [comment]
You need special rights to re-open the issue. I'll go ahead and open it.

**Comment by mirjam-amsterdam** [comment]
So, will it be possible to search within several nybc-books? in v3?

**Comment by urieli** [comment]
You can now enter multiple book references, separated by spaces.

See: https://ocr.yiddishbookcenter.org/?page=1&query=%22%D7%9B%D7%9C%D7%91+%D7%A9%D7%91%D7%9B%D7%9C%D7%91%D7%99%D7%9D%22&author=&author=%7C&authorInclude=true&title=&fromYear=&toYear=&sortBy=score&reference=nybc203711+nybc210441

**Comment by mirjam-amsterdam** [comment]
Very great!
The solution is a bit counter intuitive since authors get a field with a +
and therefore all authors end up as a list below each other. Users also
will not expect this being possible (why space and not comma or semi colon
- nobody will guess that simple space does it).
Example for usage: search for references to a certain author in Reisen's
Leksikon nybc200690, nybc200691, nybc200692, nybc200693
eg
https://ocr.yiddishbookcenter.org/?page=1&query=%D7%A0%D7%99%D7%92%D7%A2%D7%A8&author=&author=%7C&authorInclude=true&title=&fromYear=&toYear=&sortBy=score&reference=nybc200690+nybc200691+nybc200692+nybc200693
Best,
Mirjam

Mirjam Gutschow
Mariotteplein 15
1098 NW Amsterdam
Nederland
+31-20-3202086
