### ISSUE TITLE
Gershayim not recognized for phrase search, even though they're standard double quotes on some Hebrew keyboards

### ISSUE THREAD

**Issue by markhdavid** [urieli/jochre#70]
If you input the commonly used form of double quote marks on some commonly used keyboards, it inputs the Unicode character HEBREW_PUNCTUATION_GERSHAYIM. Apparently this is not considered "double quotes" for purposes of phrase search, which has doc (located here on the web)[https://github.com/urieli/jochre/wiki/Jochre-Yiddish-Search-Help]

>If you want words to follow one another in the text, you can do a phrase search, by surrounding the phrase with double quotes.

On the built-in Hebrew keyboard on MacOS (Macintosh computers) and iOS (iPhone, iPad), the gershayim character goes in when you use the key in the familiar location to the left of the return key. This is presumably true for many other keyboards.

Not having this character treated as a double quote probably will surprise and disappoint the everyday user who might want to type in a phrase. 

Even though gershayim may not be the exact correct character to use for quotation, this distinction is almost universally ignored in daily use, since the above-cited widely used Hebrew keyboards do not offer a distinct character for "double quote" vs. gershayim, or at least it's not commonly known and easily accessible.

To work around, you would have to switch to the English keyboard and type in the ASCII double quote, or figure out for a given keyboard what special method it provides, if any, to input the needed form of double quotes. 

Since the user interface is geared towards everyday users, I feel it should be fixed to treat gershayim (״) character the same as ASCII double-quote ("). It's pretty confusing to have something that looks to everyone like "double quote" not be considered so by this search system.

Meanwhile, it seems the Standards Institute of Israel defines a keyboard that does not include gershayim, and so this key is not defined for some common keyboards, most notably the Windows Hebrew keyboard.  These keyboards just have ASCII double quote. So this whole situation obviously leads to the need for modern computer systems dealing with Hebrew text to treat ASCII double quote and gershayim interchangeably. Note that this implies that ASCII double quote should be considered equivalent to gershayim where gershayim is actually the character being matched.

Example to test for comparison:

When you search With gershayim: 

> ״רבנו תּם״

the results have תם or רבנו in isolation, not together.

With ASCII double-quote:

>"רבנו תּם"

It shows only רבנו תּם next to each other, in that order, as expected.

**Comment by urieli** [comment]
Deployed on server, see https://ocr.yiddishbookcenter.org/?page=1&query=%D7%B4%D7%92%D7%90%D6%B8%D7%A8%D7%A0%D7%99%D7%A9%D7%98+%D7%A4%D7%A2%D7%A8%D7%A9%D7%98%D7%90%D6%B7%D7%A0%D7%A2%D7%9F%D7%B4&author=&author=%7C&authorInclude=true&title=&fromYear=&toYear=&sortBy=score&reference=
