### ISSUE TITLE
give option to bring up full book(s) without search term

### ISSUE THREAD

**Issue by mirjam-amsterdam** [urieli/jochre#8]
This morning I wanted to check how the books by Liptsin, Sem appear in Jochre. Since the search field is not allowed to start with * or ? I had to think of a placeholder word. That is quite annoying. I came up with "אינהאלט" but that wasn't a good idea, it retrieved far too little books: 15 out of 28.
I then tried "פאר" which already found 21 out of 28. Still not all but far better. It would be nice if I could just see all books by Sem Liptsin next to each other, without having to invent search terms.

Liptsin, Sem in NYBC-collection in archive.org: https://archive.org/search.php?query=Liptsin&and[]=languageSorter%3A%22Yiddish%22&and[]=collection%3A%22nationalyiddishbookcenter%22

https://ocr.yiddishbookcenter.org/?page=1&query=%D7%90%D7%99%D7%A0%D7%94%D7%90%D7%9C%D7%98&author=&author=%7CLiptsin%2C+Sem%7C%D7%9C%D7%99%D7%A4%D7%A6%D7%99%D7%95%2C+%D7%A1%D7%A2%D7%9D%7C%D7%9C%D7%99%D7%A4%D7%A6%D7%99%D7%9F%2C+%D7%A1%D7%A2%D7%9D%7C%D7%9C%D7%99%D7%A4%D7%A6%D7%99%D7%9F%2C%D7%A1%D7%A2%D7%9D&authorInclude=true&title=&fromYear=&toYear=&sortBy=score

https://ocr.yiddishbookcenter.org/?page=2&query=%D7%A4%D7%90%D7%A8&author=&author=%7CLiptsin%2C+Sem%7C%D7%9C%D7%99%D7%A4%D7%A6%D7%99%D7%95%2C+%D7%A1%D7%A2%D7%9D%7C%D7%9C%D7%99%D7%A4%D7%A6%D7%99%D7%9F%2C+%D7%A1%D7%A2%D7%9D%7C%D7%9C%D7%99%D7%A4%D7%A6%D7%99%D7%9F%2C%D7%A1%D7%A2%D7%9D&authorInclude=true&title=&fromYear=&toYear=&sortBy=score

**Comment by urieli** [comment]
One way to accomplish this would be to list the results differently depending on whether or not text was included in the search query. If the query is meta-data based only, the result list is simply a list of matching books, with two possible actions: show full book OCR, and a link to the book's PDF.

When we allow for meta-data correction, it will also be possible to correct the meta-data for these books.

**Comment by urieli** [comment]
Added in https://github.com/urieli/jochre/commit/44a88b458fe37ac01803a39bc586dd7a3c9ee119
