### ISSUE TITLE
Need interpretation of double-quote as gershayim (abbreviation marker), not as quoting metacharacter

### ISSUE THREAD

**Issue by markhdavid** [urieli/jochre#88]
If you search for a word with gershayim, typically entered as an ASCII double-quote ("), but properly entered as Unicode HEBREW PUNCTUATION GERSHAYIM character (U+05F4), you get a strange error. For example, searching for the following (with Gershayim character)

> פֿסס״ר

gets

> אוממעגלעך צו באַאַרבעטן דעם נאָכפֿרעג:
> Cannot parse 'פסס"ר': Lexical error at line 1, column 6. Encountered: after : "\"ר"

Same result if you use ASCII double quote, e.g.
> פֿסס"ר

It seems to be interpreting the double quotes or gershayim as an unclosed quotation metacharacter, not as a character of the word being searched. Typically, the gershayim meaning is expressed by putting it between the second-to-last and last letters of a word.

Similar examples to search for: 
> בעש״ט
> צה״ל

**Comment by urieli** [comment]
Simply leave out the gershayim for now.

Examples:

- [בעש“ט](https://ocr.yiddishbookcenter.org/?page=1&query=%D7%91%D7%A2%D7%A9%D7%98&author=&author=&authorInclude=true&title=&fromYear=&toYear=&sortBy=score&reference=)
- [פסס“ר](https://ocr.yiddishbookcenter.org/?page=1&query=%D7%A4%D7%A1%D7%A1%D7%A8&author=&author=%7C&authorInclude=true&title=&fromYear=&toYear=&sortBy=score&reference=)
