### ISSUE TITLE
How to restrict to author Aaron Glanz Leyeles

### ISSUE THREAD

**Issue by markhdavid** [urieli/jochre#91]
I would like to restrict to author Aaron Glanz Leyeles. He's very famous -- see e.g., [his Yiddish Leksikon entry](http://yleksikon.blogspot.com/2017/06/arn-leyeles-glants-arn-tuvye-arn-glants.html).  When I search: ״שויבן בליצן״ without author restriction, I get at least 1 hit for Aaron Glanz Leyeles: [Rondos un andere lider - https://archive.org/details/nybc201637](https://archive.org/details/nybc201637).

However, trying to restrict to this author did not work with various author spellings I tried:
  - Glanz-Leyeless, A. (Aaron)
  - Aaron Glanz Leyeles
  - Aaron Glanz-Leieles
  - leyeles
  - אַ לעיעלעס
  - לעיעלעס
  - לייעלעס
  - glanz
  - גלאנץ
  - גלאנז

How the heck do you find this author?

More generally if you have at least found a hit with an unrestricted search, is there some way to discover the exact spelling to use for that author from the "hit" data or metadata somehow?

**Comment by urieli** [comment]
https://ocr.yiddishbookcenter.org/?page=1&query=%D7%B0%D7%99%D7%A1%D7%9F&author=&author=%7C%7C%D7%92%D7%9C%D7%90%D6%B7%D7%A0%D7%A5%D6%BE%D7%9C%D7%A2%D7%99%D7%A2%D7%9C%D7%A2%D7%A1%2C+%D7%90%D7%94%D7%A8%D7%9F&authorInclude=true&title=&fromYear=&toYear=&sortBy=score&reference=

Here is what you do in screenshots:
![Yiddish Book Center Digital Yiddish Library Full-Text Search — Mozilla Firefox_003](https://user-images.githubusercontent.com/851962/234570859-9cd3f991-0fef-4295-bfa7-14fc93f7f670.png)
![Yiddish Book Center Digital Yiddish Library Full-Text Search — Mozilla Firefox_004](https://user-images.githubusercontent.com/851962/234570888-d10bf8ef-bcc5-4006-92bd-e46efdba6a96.png)
![Yiddish Book Center Digital Yiddish Library Full-Text Search — Mozilla Firefox_005](https://user-images.githubusercontent.com/851962/234570897-bb5e5e5d-f711-4d03-b868-580762fff2b7.png)

More generally: in the hit you find, there will be a field "מחבר". You copy the text, clock on "אַװאַנסירטער נאָכזוך", paste it inside the "מחבר" field, select the author, click on the "+" button, and run the search.
